### ISSUE TITLE
Review varint binary serialization, test golang against C++

### ISSUE THREAD

**Issue by theoreticalbts** [koinos/koinos-types#177]
It seems `to_binary()` [here](https://github.com/koinos/koinos-types/blob/2cba96077317075e2f53e8ba268abba16a2c5477/programs/koinos-types/lang/koinos_codegen_cpp/rt/binary.hpp#L137-L156) has a couple issues:

- (1) It seems to write in little-endian order, but I believe golang lib uses big-endian order.
- (2) Loop at the end pointlessly writes one byte at a time, let's instead do `s.write(tmp, len+1)`

We must not be testing golang against C++ for binary serialization.

**Comment by mvandeberg** [comment]
Commit d68d9e88343cb847fde46059b925b42c87fc01d8 might have addressed this issue
