### ISSUE TITLE
Rename transaction_record to transaction_item

### ISSUE THREAD

**Issue by theoreticalbts** [koinos/koinos-types#217]
[This transaction_store PR](https://github.com/koinos/koinos-transaction-store/pull/6) and #216 implement `get_transaction_response` as a vector of `transaction_record`.

Until now, the convention used (mostly in `block_store`) is that types called `*record` are an implementation detail of a particular on-disk format backend.  A type named `*record` *should not* be used in an RPC definition.

In situations where the on-disk record is identical to the RPC response, I personally think it makes more sense to still have two separate types, and assign them member-by-member.

However, I can see the view that splitting a type into two identical types is "premature architecturization."  If we end up deciding in favor of this view and having a single type for both RPC responses and on-disk format, I'd still prefer to rename the type to something besides `*record` today.  Then we can rename the on-disk format back to `*record` if we decide at some future time to make the disk / RPC formats be different.

In the ticket title, I proposed changing `record` to `item`.  But I'm open to other suggestions.

**Comment by mvandeberg** [comment]
Handled in capn'proto work.
