### ISSUE TITLE
Default initialization of integer fields

### ISSUE THREAD

**Issue by theoreticalbts** [koinos/koinos-types#32]
Currently integer fields aren't initialized in generated code.  There are two ways this can be achieved:

- (1) Instead of simple `typedef` of built-in integer types, integer types in `basetypes.hpp` should instead be custom types with proper default initializers (and presumably all arithmetic operators).
- (2) Add code generator functionality to the C++ backend to default initialize fields of integer types, or typedefs of integer types.

Approach (2) will probably require extending the basetype declaration syntax to give us a way to tell the codegen "this type has this default initializer".

**Comment by mvandeberg** [comment]
Ran in to this bug when implementing #162

I am re-opening in support of the second solution.
